abbreviations_dict = {
    "ang": "Ángulo",
    "bar": "Diámetro de barra",
    "blk": "Bloqueo de línea",
    "cfd": "Avance de corte normal",
    "cfr": "Dimensión del chaflán (bisel)",
    "chk": "Posición de sujeción del husillo",
    "clt": "Método de recolección de parte",
    "cnt": "Contador acumulativo",
    "cof": "Herramienta de tronzado",
    "col": "Acciones de la boquilla",
    "com": "Comentario",
    "cut": "Profundidad por corte",
    "cyl": "Ciclo de mecanizado",
    "dia": "Diámetro",
    "dim": "Dimensión",
    "dpt": "Profundidad de corte",
    "dsc": "Descripción del programa",
    "dwl": "Tiempo de espera",
    "dyr": "Dirección del movimiento de corte",
    "fed": "Velocidad de avance de corte",
    "fre": "Línea de código libre",
    "grd": "Dimensión en grados de rotación",
    "lcr": "Posición actual eje longitudinal",
    "lcm": "Compensación de posición eje longitudinal",
    "ldn": "Letra de denominación eje longitudinal",
    "lds": "Desplazamiento eje longitudinal",
    "lin": "Punto inicio eje longitudinal",
    "lgt": "Longitud",
    "lmd": "Modificador de signo eje longitudinal",
    "lnd": "Punto final eje longitudinal",
    "lsc": "Posición seguridad eje longitudinal",
    "lst": "Punto de partida eje longitudinal",
    "mat": "Cantidad de material a mecanizar",
    "mcd": "Códigos M",
    "mch": "Tipo de máquina",
    "mnp": "Número de programa principal",
    "mov": "Tipo de movimiento",
    "mta": "Indicador de programa principal activo",
    "ovr": "Sobre material para acabado",
    "pgr": "Número de programa",
    "plt": "Datos de la platina",
    "pos": "Posición de los cortes en eje transversal",
    "rep": "Número de repeticiones",
    "rgh": "Indicador de desbaste",
    "rot": "Sentido de rotación",
    "rtr": "Punto de retracción",
    "sde": "Lado del programa",
    "seq": "Número de secuencia",
    "sfd": "Avance de corte inicial",
    "spc": "Indicaciones especiales",
    "spd": "Velocidad de giro",
    "stp": "Parada programada",
    "sub": "Número de subrutina",
    "sys": "Sistema de coordenadas",
    "tcr": "Posición actual eje transversal",
    "tcm": "Compensación de posición eje transversal",
    "tdn": "Letra de denominación eje transversal",
    "tds": "Desplazamiento eje transversal",
    "tfd": "Avance de corte entrada transversal",
    "thd": "Dimensión de la rosca",
    "tin": "Punto inicio eje transversal",
    "tmd": "Modificador de signo eje transversal",
    "tnd": "Punto final eje transversal",
    "tol": "Número de herramienta",
    "trn": "Comando de sincronización K16",
    "tsc": "Posición seguridad eje transversal",
    "tst": "Punto de partida eje transversal",
    "typ": "Tipo de herramienta",
    "wdt": "Espesor o ancho",
    "wrk": "Puntos prefijados de trabajo",
    "xcn": "Punto centro del arco eje X",
    "xin": "Punto inicio eje X",
    "xps": "Posición en eje X",
    "ycn": "Punto centro del arco eje Y",
    "yin": "Punto inicio eje Y",
    "yps": "Posición en eje Y",
    "zcn": "Punto centro del arco eje Z",
    "zin": "Punto inicio eje Z",
    "znd": "Punto final eje Z",
    "zps": "Posición en eje Z",
}
