swiss_m_codes = {
    "": "",
    "PARADA PROGRAMADA": "M00",
    "PARADA OPCIONAL": "M01",
    "GIRO NORMAL": "M03",
    "GIRO REVERSA": "M04",
    "GIRO DETENER": "M05",
    "CERRAR BOQUILLA": "M06",
    "ABRIR BOQUILLA": "M07",
    "ACTIVAR REFRIGERANTE": "M08",
    "DESACTIVAR REFRIGERANTE": "M09",
    "INICIO PERFORADO": "",
}

swiss_g_codes = {
    "": "",
    "MOVIMIENTO RAPIDO": "G00",
    "MOVIMIENTO CORTE": "G01",
    "GIRO A FAVOR": "G02",
    "GIRO EN CONTRA": "G03",
    "COMPENSACION IZQUIERDA": "G41",
    "COMPENSACION DERECHA": "G42",
    "COMPENSACION CANCELAR": "G40",
    "SISTEMA ABSOLUTO": "G90",
    "SISTEMA INCREMENTAL": "G91",
}

lathe_g_codes = {
    "": "",
    "MOVIMIENTO RAPIDO": "G00",
    "MOVIMIENTO CORTE": "G01",
    "GIRO A FAVOR": "G02",
    "GIRO EN CONTRA": "G03",
    "COMPENSACION IZQUIERDA": "G41",
    "COMPENSACION DERECHA": "G42",
    "COMPENSACION CANCELAR": "G40",
    "SISTEMA ABSOLUTO": "G90",
    "SISTEMA INCREMENTAL": "G91",
}

mill_g_codes = {
    "": "",
    "MOVIMIENTO RAPIDO": "G00",
    "MOVIMIENTO CORTE": "G01",
    "GIRO A FAVOR": "G02",
    "GIRO EN CONTRA": "G03",
    "COMPENSACION IZQUIERDA": "G41",
    "COMPENSACION DERECHA": "G42",
    "COMPENSACION CANCELAR": "G40",
    "SISTEMA ABSOLUTO": "G90",
    "SISTEMA INCREMENTAL": "G91",
    "Z INICIAL": "G98",
    "PUNTO RETRACCION": "G99",
}

swiss_k_m_codes = {
    "": "",
    "PARADA PROGRAMADA": "M00",
    "PARADA OPCIONAL": "M01",
    "GIRO NORMAL $1": "M03",
    "GIRO REVERSA $1": "M04",
    "GIRO DETENER $1": "M05",
    "CERRAR BOQUILLA $1": "M06",
    "ABRIR BOQUILLA $1": "M07",
    "ACTIVAR REFRIGERANTE": "M08",
    "DESACTIVAR REFRIGERANTE": "M09",
    "CERRAR BOQUILLA $2": "M15",
    "ABRIR BOQUILLA $2": "M16",
    "GIRO NORMAL $2": "M23",
    "GIRO REVERSA $2": "M24",
    "GIRO DETENER $2": "M25",
    "GIRO NORMAL $3": "M80",
    "GIRO REVERSA $3": "M81",
    "GIRO DETENER $3": "M82",
    "INICIO PERFORADO": "M140",
    "CERRAR BOQUILLA $3": "",
    "ABRIR BOQUILLA $3": "",
}

omni_m_codes = {
    "": "",
    "PARADA PROGRAMADA": "M00",
    "PARADA OPCIONAL": "M01",
    "GIRO NORMAL": "M03",
    "GIRO REVERSA": "M04",
    "GIRO DETENER": "M05",
    "CERRAR BOQUILLA": "M12",
    "ABRIR BOQUILLA": "M13",
    "ACTIVAR REFRIGERANTE": "M08",
    "DESACTIVAR REFRIGERANTE": "M09",
    "INICIO PERFORADO": "",
}

romi_m_codes = {
    "": "",
    "PARADA PROGRAMADA": "M00",
    "PARADA OPCIONAL": "M01",
    "GIRO NORMAL": "M03",
    "GIRO REVERSA": "M04",
    "GIRO DETENER": "M05",
    "ACTIVAR REFRIGERANTE": "M08",
    "DESACTIVAR REFRIGERANTE": "M09",
    "ABRIR BOQUILLA": "M24",
    "CERRAR BOQUILLA": "M25",
    "INICIO PERFORADO": "",
}

hardinge_m_codes = {
    "": "",
    "PARADA PROGRAMADA": "M00",
    "PARADA OPCIONAL": "M01",
    "GIRO NORMAL": "M03",
    "GIRO REVERSA": "M04",
    "GIRO DETENER": "M05",
    "ACTIVAR REFRIGERANTE": "M08",
    "DESACTIVAR REFRIGERANTE": "M09",
    "ABRIR BOQUILLA": "M21",
    "CERRAR BOQUILLA": "M22",
    "INICIO PERFORADO": "",
}

mazak_m_codes = {
    "": "",
    "PARADA PROGRAMADA": "M00",
    "PARADA OPCIONAL": "M01",
    "GIRO NORMAL": "M03",
    "GIRO REVERSA": "M04",
    "GIRO DETENER": "M05",
    "ACTIVAR REFRIGERANTE": "M08",
    "DESACTIVAR REFRIGERANTE": "M09",
    "CERRAR BOQUILLA": "",
    "ABRIR BOQUILLA": "",
    "INICIO PERFORADO": "",
}
