swiss_m_codes = [["Cód", "Descripción"], ["M00", "Parada programada"]]

kswiss_m_codes = [["Cód", "Descripción"], ["M00", "Parada programada"]]

romi_m_codes = [
    ["Cód", "Descripción"],
    ["M00", "Parada programada"],
    ["M01", "Parada opcional"],
    ["M02", "Fin de programa"],
    ["M03", "Giro de husillo en sentido horario"],
    ["M04", "Giro de husillo en sentido antihorario"],
    ["M05", "Desactiva giro de husillo"],
    ["M07", "Bomba de refrigerante 2"],
    ["M08", "Bomba de refrigerante 1"],
    ["M09", "Detiene bomba de refrigerante"],
    ["M18", "Desactiva orientación de husillo"],
    ["M19", "Orientación de husillo / Eje C"],
    ["M20", "Activa alimentación de barra"],
    ["M21", "Desactiva alimentación de barra"],
    ["M22", "Activa freno de husillo"],
    ["M23", "Desactiva freno de husillo"],
    ["M24", "Abre boquilla"],
    ["M25", "Cierra boquilla"],
    ["M28", "Desactiva macho flotante"],
    ["M29", "Macho rígido / Flotante"],
    ["M30", "Fin de programa con retorno a inicio"],
    ["M34", "Activa transportador de viruta"],
    ["M35", "Desactiva transportador de viruta"],
    ["M36", "Abre puerta automática"],
    ["M37", "Cierra puerta automática"],
    ["M40", "Activa boquilla sujeción interna"],
    ["M41", "Activa boquilla sujeción externa"],
    ["M45", "Activa limpieza de protecciones"],
    ["M46", "Desactiva limpieza de protecciones"],
    ["M49", "Cambio de barra"],
    ["M76", "Contador de piezas"],
    ["M80", "Salto condicional"],
    ["M93", "Activa lectura de programa vía PCIMCA"],
    ["M94", "Desactiva lectura de programa vía PCIMCA"],
    ["M98", "Llama subrutina"],
    ["M99", "Retorno a inicio de programa sin finalizar"],
]

hardinge_m_codes = [
    ["Cód", "Descripción"],
    ["M00", "Parada programada"],
    ["M01", "Parada opcional"],
    ["M03", "Giro de husillo en sentido horario"],
    ["M04", "Giro de husillo en sentido antihorario"],
    ["M05", "Desactiva giro de husillo"],
    ["M08", "Bomba de refrigerante"],
    ["M09", "Detiene bomba de refrigerante"],
    ["M13", "Giro de husillo en sentido horario con refrigerante"],
    ["M14", "Giro de husillo en sentido antihorario con refrigerante"],
    ["M17", "Activa refrigerante husillo"],
    ["M18", "Desactiva refrigerante husillo"],
    ["M21", "Abre boquilla"],
    ["M22", "Cierra boquilla"],
    ["M28", "Activa boquilla sujeción externa"],
    ["M29", "Activa boquilla sujeción interna"],
    ["M30", "Fin de programa con retorno a inicio"],
    ["M31", "Retorna a inicio y reinicia programa"],
    ["M42", "Desactiva redondeo de esquinas"],
    ["M43", "Activa redondeo de esquinas"],
    ["M44", "Activa torreta indexable bidireccional"],
    ["M45", "Desactiva torreta indexable bidireccional"],
    ["M48", "Activa sobrecarga de avance y giro"],
    ["M49", "Desactiva sobrecarga de avance y giro"],
    ["M84", "Avance de contrapunta"],
    ["M85", "Retroceso de contrapunta"],
    ["M86", "Retroceso de contrapunta a posición Home"],
    ["M94", "Llama subrutina"],
    ["M99", "Retorno a inicio de programa sin finalizar"],
]

omni_m_codes = [["Cód", "Descripción"], ["M00", "Parada programada"]]

mill_m_codes = [
    ["Cód", "Descripción"],
    ["M00", "Parada programada"],
    ["M01", "Parada opcional"],
    ["M02", "Fin de programa"],
    ["M03", "Giro de husillo en sentido horario"],
    ["M04", "Giro de husillo en sentido antihorario"],
    ["M05", "Desactiva giro de husillo"],
    ["M06", "Cambio de herramienta"],
    ["M07", "Bomba de refrigerante en spray"],
    ["M08", "Bomba de refrigerante en chorro"],
    ["M09", "Detiene bomba de refrigerante"],
    ["M10", "Sujeción de herramienta en husillo"],
    ["M11", "Desactiva sujeción de herramienta en husillo"],
    ["M15", "Cerrar cobertor de magazine"],
    ["M16", "Abrir cobertor de magazine"],
    ["M19", "Activa orientación de husillo"],
    ["M23", "Activa detección de errores"],
    ["M24", "Desactiva detección de errores"],
    ["M30", "Fin de programa con retorno a inicio"],
    ["M33", "Avance de medidor de altura de herramienta"],
    ["M34", "Retroceso de medidor de altura de herramienta"],
    ["M35", "Detección de quiebre de herramienta"],
    ["M36", "Selección de velocidad de giro (baja)"],
    ["M37", "Selección de velocidad de giro (baja-media)"],
    ["M38", "Selección de velocidad de giro (baja-media-alta)"],
    ["M39", "Selección de velocidad de giro (alta)"],
    ["M40", "Selección de velocidad de giro (neutra)"],
    ["M42", "Rotación inversa de la mesa de trabajo indexable"],
    ["M43", "Comando externo 3"],
    ["M44", "Comando externo 4"],
    ["M45", "Comando externo 5"],
    ["M48", "Activa corrección de avance y velocidad de giro"],
    ["M49", "Desactiva corrección de avance y velocidad de giro"],
    ["M50", "Bomba de aire"],
    ["M51", "Bomba de refrigerante através del husillo"],
    ["M52", "Bomba de refrigerante para roscado"],
    ["M58", "Verificación de vida útil de herramienta"],
    ["M64", "Cerrar puerta de paletizadora"],
    ["M65", "Abrir puerta de paletizadora"],
    ["M68", "Activar sujeción de paletizadora"],
    ["M69", "Desactivar sujeción de paletizadora"],
    ["M71", "Selección de paleta 1"],
    ["M72", "Selección de paleta 2"],
    ["M73", "Selección de paleta 3"],
    ["M74", "Selección de paleta 4"],
    ["M75", "Selección de paleta 5"],
    ["M76", "Selección de paleta 6"],
    ["M90", "Cancela imagen espejo (MAZATROL)"],
    ["M91", "Imagen espejo X (MAZATROL)"],
    ["M92", "Imagen espejo Y (MAZATROL)"],
    ["M93", "Imagen espejo 4 (MAZATROL)"],
    ["M98", "Llama subrutina"],
    ["M99", "Finalizar subrutina"],
    ["100", "Comando externo 1"],
    ["101", "Comando externo 2"],
    ["122", "Activa dispositivo Play Take-up"],
    ["123", "Desctiva dispositivo Play Take-up"],
    ["130", "Activa bomba de refrigerante Niagara"],
    ["132", "Bomba de aire através del husillo"],
]
